apiVersion: v1
kind: Template
metadata:
  name: selectorsyncset-template

parameters:
  - name: REGISTRY_IMG
    required: true
  - name: CHANNEL
    value: staging
    required: true
  - name: IMAGE_TAG
    required: true
  - name: REPO_NAME
    value: managed-upgrade-operator
    required: true

objects:
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      labels:
        managed.openshift.io/gitHash: ${IMAGE_TAG}
        managed.openshift.io/gitRepoName: ${REPO_NAME}
        managed.openshift.io/osd: "true"
      name: managed-upgrade-operator
    spec:
      clusterDeploymentSelector:
        matchLabels:
          api.openshift.com/managed: "true"
      resourceApplyMode: Sync
      resources:
        - apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-managed-upgrade-operator
            labels:
              openshift.io/cluster-monitoring: "true"
        - apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: managed-upgrade-operator
            namespace: openshift-managed-upgrade-operator
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: managed-upgrade-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - serviceaccounts
                - services/finalizers
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - nodes
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - deployments
                - deployments/finalizers
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - upgrade.managed.openshift.io
              resources:
                - "*"
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - config.openshift.io
              resources:
                - "*"
              verbs:
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - machine.openshift.io
              resources:
                - machines
                - machinesets
              verbs:
                - "*"
            - apiGroups:
                - machineconfiguration.openshift.io
              resources:
                - machineconfigpools
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - operators.coreos.com
              resources:
                - subscriptions
              verbs:
                - "*"
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - "*"
        - kind: ClusterRoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: managed-upgrade-operator-crb
          subjects:
            - kind: ServiceAccount
              name: managed-upgrade-operator
              namespace: openshift-managed-upgrade-operator
          roleRef:
            kind: ClusterRole
            name: managed-upgrade-operator
            apiGroup: rbac.authorization.k8s.io
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: prometheus-k8s
            namespace: openshift-managed-upgrade-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - services
                - endpoints
                - pods
              verbs:
                - get
                - list
                - watch
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: prometheus-k8s
            namespace: openshift-managed-upgrade-operator
          roleRef:
            kind: Role
            name: prometheus-k8s
          subjects:
            - kind: ServiceAccount
              name: prometheus-k8s
              namespace: openshift-monitoring
        - apiVersion: operators.coreos.com/v1alpha1
          kind: CatalogSource
          metadata:
            name: managed-upgrade-operator-catalog
            namespace: openshift-managed-upgrade-operator
          spec:
            sourceType: grpc
            image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
            displayName: Managed Upgrade Operator
            publisher: Red Hat
        - apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: managed-upgrade-operator-og
            namespace: openshift-managed-upgrade-operator
          spec:
            targetNamespaces:
              - openshift-managed-upgrade-operator
        - apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: managed-upgrade-operator
            namespace: openshift-managed-upgrade-operator
          spec:
            channel: ${CHANNEL}
            name: managed-upgrade-operator
            source: managed-upgrade-operator-catalog
            sourceNamespace: openshift-managed-upgrade-operator
        - apiVersion: apiextensions.k8s.io/v1
          kind: CustomResourceDefinition
          metadata:
            name: upgradeconfigs.upgrade.managed.openshift.io
          spec:
            group: upgrade.managed.openshift.io
            names:
              kind: UpgradeConfig
              listKind: UpgradeConfigList
              plural: upgradeconfigs
              shortNames:
                - upgrade
              singular: upgradeconfig
            scope: Cluster
            versions:
              - additionalPrinterColumns:
                  - jsonPath: .spec.desired.version
                    name: desired_version
                    type: string
                  - jsonPath: .status.history[0].phase
                    name: phase
                    type: string
                  - jsonPath: .status.history[0].conditions[0].type
                    name: stage
                    type: string
                  - jsonPath: .status.history[0].conditions[0].status
                    name: status
                    type: string
                  - jsonPath: .status.history[0].conditions[0].reason
                    name: reason
                    type: string
                  - jsonPath: .status.history[0].conditions[0].message
                    name: message
                    type: string
                name: v1alpha1
                schema:
                  openAPIV3Schema:
                    description: UpgradeConfig is the Schema for the upgradeconfigs API
                    properties:
                      apiVersion:
                        description:
                          "APIVersion defines the versioned schema of this representation
                          of an object. Servers should convert recognized schemas to the latest
                          internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
                        type: string
                      kind:
                        description:
                          "Kind is a string value representing the REST resource this
                          object represents. Servers may infer this from the endpoint the client
                          submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
                        type: string
                      metadata:
                        type: object
                      spec:
                        description:
                          UpgradeConfigSpec defines the desired state of UpgradeConfig
                          and upgrade window and freeze window
                        properties:
                          PDBForceDrainTimeout:
                            default: 60
                            description:
                              The maximum grace period granted to a node whose drain
                              is blocked by a Pod Disruption Budget, before that drain is forced.
                              Measured in minutes.
                            format: int32
                            type: integer
                          desired:
                            description: Specify the desired OpenShift release
                            properties:
                              channel:
                                description: Channel we gonna use for upgrades
                                type: string
                              force:
                                default: false
                                description: Force upgrade, default value is False
                                type: boolean
                              version:
                                description: Version of openshift release
                                type: string
                            required:
                              - channel
                              - force
                              - version
                            type: object
                          proceed:
                            default: true
                            description:
                              Given all conditions have passed and cluster is ready
                              to upgrade, proceed governs this decision to continue and commence
                              the upgrade
                            type: boolean
                          subscriptionUpdates:
                            description: This defines the 3rd party operator subscriptions upgrade
                            items:
                              description: SubscriptionUpdate describe the 3rd party operator update config
                              properties:
                                channel:
                                  description: Describe the channel for the Subscription
                                  type: string
                                name:
                                  description: Describe the name of the Subscription
                                  type: string
                                namespace:
                                  description: Describe the namespace of the Subscription
                                  type: string
                              required:
                                - channel
                                - name
                                - namespace
                              type: object
                            type: array
                          type:
                            description: Type indicates the ClusterUpgrader implementation to use to perform an upgrade of the cluster
                            enum:
                              - OSD
                            type: string
                          upgradeAt:
                            description: Specify the upgrade start time
                            type: string
                        required:
                          - PDBForceDrainTimeout
                          - desired
                          - proceed
                          - type
                          - upgradeAt
                        type: object
                      status:
                        description: UpgradeConfigStatus defines the observed state of UpgradeConfig
                        properties:
                          history:
                            description: This record history of every upgrade
                            items:
                              description: UpgradeHistory record history of upgrade
                              properties:
                                completeTime:
                                  format: date-time
                                  type: string
                                conditions:
                                  description: Conditions is a set of Condition instances.
                                  items:
                                    properties:
                                      completeTime:
                                        description: Complete time of this condition.
                                        format: date-time
                                        type: string
                                      lastProbeTime:
                                        description: Last time the condition was checked.
                                        format: date-time
                                        type: string
                                      lastTransitionTime:
                                        description: Last time the condition transit from one
                                          status to another.
                                        format: date-time
                                        type: string
                                      message:
                                        description: Human readable message indicating details
                                          about last transition.
                                        type: string
                                      reason:
                                        description: (brief) reason for the condition's last transition.
                                        type: string
                                      startTime:
                                        description: Start time of this condition.
                                        format: date-time
                                        type: string
                                      status:
                                        description: Status of condition, one of True, False,
                                          Unknown
                                        type: string
                                      type:
                                        description: Type of upgrade condition
                                        type: string
                                    required:
                                      - status
                                      - type
                                    type: object
                                  type: array
                                phase:
                                  default: New
                                  description: This describe the status of the upgrade process
                                  enum:
                                    - New
                                    - Pending
                                    - Upgrading
                                    - Upgraded
                                    - Failed
                                  type: string
                                startTime:
                                  format: date-time
                                  type: string
                                version:
                                  description: Desired version of this upgrade
                                  type: string
                              required:
                                - phase
                              type: object
                            type: array
                        type: object
                    type: object
                served: true
                storage: true
                subresources:
                  status: {}
