apiVersion: v1
kind: Template
metadata:
  name: selectorsyncset-template

parameters:
  - name: REGISTRY_IMG
    required: true
  - name: CHANNEL
    value: staging
    required: true
  - name: IMAGE_TAG
    required: true
  - name: REPO_NAME
    value: managed-upgrade-operator
    required: true

objects:
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      labels:
        managed.openshift.io/gitHash: ${IMAGE_TAG}
        managed.openshift.io/gitRepoName: ${REPO_NAME}
        managed.openshift.io/osd: "true"
      name: managed-upgrade-operator
    spec:
      clusterDeploymentSelector:
        matchLabels:
          api.openshift.com/managed: "true"
      resourceApplyMode: Sync
      resources:
        - apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-managed-upgrade-operator
            labels:
              openshift.io/cluster-monitoring: "true"
        - apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: managed-upgrade-operator
            namespace: openshift-managed-upgrade-operator
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: managed-upgrade-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - serviceaccounts
                - services/finalizers
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - nodes
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - deployments
                - deployments/finalizers
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - upgrade.managed.openshift.io
              resources:
                - "*"
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - config.openshift.io
              resources:
                - "*"
              verbs:
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - machine.openshift.io
              resources:
                - machines
                - machinesets
              verbs:
                - "*"
            - apiGroups:
                - machineconfiguration.openshift.io
              resources:
                - machineconfigpools
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - operators.coreos.com
              resources:
                - subscriptions
              verbs:
                - "*"
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - "*"
        - kind: ClusterRoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: managed-upgrade-operator-crb
          subjects:
            - kind: ServiceAccount
              name: managed-upgrade-operator
              namespace: openshift-managed-upgrade-operator
          roleRef:
            kind: ClusterRole
            name: managed-upgrade-operator
            apiGroup: rbac.authorization.k8s.io
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: prometheus-k8s
            namespace: openshift-managed-upgrade-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - services
                - endpoints
                - pods
              verbs:
                - get
                - list
                - watch
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: prometheus-k8s
            namespace: openshift-managed-upgrade-operator
          roleRef:
            kind: Role
            name: prometheus-k8s
          subjects:
            - kind: ServiceAccount
              name: prometheus-k8s
              namespace: openshift-monitoring
        - apiVersion: operators.coreos.com/v1alpha1
          kind: CatalogSource
          metadata:
            name: managed-upgrade-operator-catalog
            namespace: openshift-managed-upgrade-operator
          spec:
            sourceType: grpc
            image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
            displayName: Managed Upgrade Operator
            publisher: Red Hat
        - apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: managed-upgrade-operator-og
            namespace: openshift-managed-upgrade-operator
          spec:
            targetNamespaces:
              - openshift-managed-upgrade-operator
        - apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: managed-upgrade-operator
            namespace: openshift-managed-upgrade-operator
          spec:
            channel: ${CHANNEL}
            name: managed-upgrade-operator
            source: managed-upgrade-operator-catalog
            sourceNamespace: openshift-managed-upgrade-operator
