apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-upgrade-operator-config
data:
  config.yaml: |
    maintenance:
      controlPlaneTime: 90
      ignoredAlerts:
        controlPlaneCriticals:
        - etcdMembersDown
        - KubeDeploymentReplicasMismatch
        - ClusterOperatorDown
        - MachineWithNoRunningPhase
        - ClusterOperatorDegraded
    scale:
      timeOut: 30
    upgradeWindow:
      delayTrigger: 30
      timeOut: 120
    nodeDrain:
      timeOut: 45
      expectedNodeDrainTime: 8
    healthCheck:
      ignoredCriticals:
      - DNSErrors05MinSRE
      - MetricsClientSendFailingSRE
      - UpgradeNodeScalingFailedSRE
      - UpgradeClusterCheckFailedSRE
    verification:
      ignoredNamespaces:
      - openshift-logging
      namespacePrefixesToCheck:
      - openshift
      - kube
      - default
